accounts/urls.py
import accounts.views as aviews
from django.urls import path

app_name = 'accounts'
urlpatterns = [
    path('inscription/', aviews.Inscription.as_view(), name='inscription'),
    path('mon-compte/', aviews.MonCompte.as_view(), name='mon-compte'),
    path('logs/', aviews.AccessLogs.as_view(), name='access-logs'),
]

orgues/urls.py
from django.urls import path

import orgues.views as v

app_name = 'orgues'
urlpatterns = [
    path('orgues/', v.OrgueList.as_view(), name='orgue-list'),
    path('orgues/csv/', v.OrgueExport.as_view(), name='orgue-csv'),
    path('recherche/', v.OrgueSearch.as_view(), name='orgue-search'),
    path('liste.json', v.OrgueListJS.as_view(), name='orgue-list-js'),
    path('etats.json', v.OrgueEtatsJS.as_view(), name='orgue-etats-js'),
    path('etats2.json', v.OrgueEtatsJSDep.as_view(), name='orgue-etats-js2'),
    path('references_palissy.json', v.OrgueHistJS.as_view(), name='orgue-hist-js'),
    path('references_palissyDep.json', v.OrgueHistJSDep.as_view(), name='orgue-histDep-js'),
    path('carte/', v.OrgueCarte.as_view(), name='orgue-carte'),
    path('detail/<slug:slug>/', v.OrgueDetail.as_view(), name='orgue-detail'),
    path('detail/<slug:slug>/qrcode', v.OrgueQrcode.as_view(), name='orgue-qrcode'),
    path('exemple/', v.OrgueDetailExemple.as_view(), name='orgue-detail-exemple'),
    path('conseils/', v.ConseilsFicheView.as_view(),name='orgue-fiche-conseils'),
    path('orgues/filtre', v.OrgueFiltreJS.as_view(), name='orgue-filtre-js'),
    path('avancement.json', v.Avancement.as_view(), name = 'orgue-av-js'),

    # Administration
    path('creation/', v.OrgueCreate.as_view(), name='orgue-create'),
    path('edition/<uuid:orgue_uuid>/', v.OrgueUpdate.as_view(), name='orgue-update'),
    path('edition/instrumentale/<uuid:orgue_uuid>/', v.OrgueUpdateInstrumentale.as_view(), name='orgue-update-instrumentale'),
    path('edition/composition/<uuid:orgue_uuid>/', v.OrgueUpdateComposition.as_view(), name='orgue-update-composition'),
    path('edition/avancement/<uuid:orgue_uuid>/', v.OrgueDetailAvancement.as_view(), name='orgue-detail-avancement'),
    path('edition/contributions/<uuid:orgue_uuid>/', v.OrgueDetailContributions.as_view(), name='orgue-detail-contributions'),
    path('edition/buffet/<uuid:orgue_uuid>/', v.OrgueUpdateBuffet.as_view(), name='orgue-update-buffet'),
    path('edition/localisation/<uuid:orgue_uuid>/', v.OrgueUpdateLocalisation.as_view(), name='orgue-update-localisation'),
    path('suppression/<uuid:orgue_uuid>/', v.OrgueDelete.as_view(), name='orgue-delete'),
    path('dashboard/', v.Dashboard.as_view(), name='dashboard'),

    # Tableau de bord
    #path('orgues/dashboard', v.OrgueDashboard.as_view(), name='orgue-dashboard'),

    # Evenements
    path('evenements/<uuid:orgue_uuid>/', v.EvenementList.as_view(), name='evenement-list'),
    path('evenement/edition/<int:pk>/', v.EvenementUpdate.as_view(), name='evenement-update'),
    path('evenement/creation/<uuid:orgue_uuid>/', v.EvenementCreate.as_view(), name='evenement-create'),
    path('evenement/suppression/<int:pk>/', v.EvenementDelete.as_view(), name='evenement-delete'),

    # claviers
    path('clavier/creation/<uuid:orgue_uuid>/', v.ClavierCreate.as_view(), name='clavier-create'),
    path('clavier/edition/<int:pk>/', v.ClavierUpdate.as_view(), name='clavier-update'),
    path('clavier/suppression/<int:pk>/', v.ClavierDelete.as_view(), name='clavier-delete'),

    # facteurs
    path('listeFacteur.json', v.FacteurListJSLeaflet.as_view(), name='facteur-list-js-leaflet'),
    path('js/facteurs/', v.FacteurListJS.as_view(), name='facteur-list-js'),
    path('js/facteurs/creation/', v.FacteurCreateJS.as_view(), name='facteur-create-js'),
    path('js/facteurs/lonlat/', v.FacteurListJSlonlat.as_view(), name='facteur-list-js-lonlat'),
    path('js/facteurs/lonlatLeaflet/', v.FacteurLonLatLeaflet.as_view(), name='facteur-js-lonlat'),

    # types jeux
    path('types_jeux/creation/', v.TypeJeuCreateJS.as_view(), name='typejeu-create-js'),
    path('types_jeux/edition/<int:pk>/', v.TypeJeuUpdate.as_view(), name='typejeu-update'),
    path('js/liste/jeux/', v.TypeJeuListJS.as_view(), name='typejeu-list-js'),

    # fichiers
    path('fichiers/<uuid:orgue_uuid>/', v.FichierList.as_view(), name='fichier-list'),
    path('fichiers/creation/<uuid:orgue_uuid>/', v.FichierCreate.as_view(), name='fichier-create'),
    path('fichiers/suppression/<int:pk>/', v.FichierDelete.as_view(), name='fichier-delete'),

    # images
    path('images/<uuid:orgue_uuid>/', v.ImageList.as_view(), name='image-list'),
    path('images/creation/<uuid:orgue_uuid>/', v.ImageCreate.as_view(), name='image-create'),
    path('images/update/<int:pk>/', v.ImageUpdate.as_view(), name='image-update'),
    path('images/suppression/<int:pk>/', v.ImageDelete.as_view(), name='image-delete'),
    path('images/principale/<int:pk>/', v.ImagePrincipaleUpdate.as_view(), name='image-principale'),

    # Sources
    path('sources/<uuid:orgue_uuid>/', v.SourceList.as_view(), name='source-list'),
    path('source/edition/<int:pk>/', v.SourceUpdate.as_view(), name='source-update'),
    path('source/creation/<uuid:orgue_uuid>/', v.SourceCreate.as_view(), name='source-create'),
    path('source/suppression/<int:pk>/', v.SourceDelete.as_view(), name='source-delete'),

    path('searchlog/', v.SearchLogView.as_view(), name='search-log'),

    #Création d'orgue
    path('js/communes/', v.CommuneListJS.as_view(), name='commune-list-js'),
    path('js/designation/', v.DesignationListJS.as_view(), name='designation-list-js')
]

templates/base.html
{% load static %}
{% load fabtags %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta name="viewport" content="width=device-width, initial-scale=1"/>
  <meta http-equiv="content-type" content="text/html; charset=utf-8"/>
  <meta name="author" content="Fabdev"/>
  <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type='image/x-icon'>
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  {% block meta_tags %}
  <title>Inventaire national des orgues</title>
  <meta name="description" content="La France compte plus de 8500 orgues sur tout le territoire national, dont plus de 1600 sont classés ou inscrits au titre des monuments historiques. La beauté et la diversité de ses orgues sont reconnues dans le monde entier. En plus de mettre en avant la grande qualité de la facture d'orgue française, ce patrimoine offre un éventail complet de toutes les créations artistiques témoins des écoles européennes à travers le temps.L’inventaire des orgues a pour objectif de rassembler de manière collaborative sur un site internet dédié toutes les données actuellement disponibles sur les orgues en France.">
  <meta property="og:title" content="Inventaire national des orgues">
  <meta property="og:description" content="La France compte plus de 8500 orgues sur tout le territoire national, dont plus de 1600 sont classés ou inscrits au titre des monuments historiques. La beauté et la diversité de ses orgues sont reconnues dans le monde entier. En plus de mettre en avant la grande qualité de la facture d'orgue française, ce patrimoine offre un éventail complet de toutes les créations artistiques témoins des écoles européennes à travers le temps.L’inventaire des orgues a pour objectif de rassembler de manière collaborative sur un site internet dédié toutes les données actuellement disponibles sur les orgues en France.">
  <meta property="og:image" content="{% static 'img/orgue_illustration_enfants.jpg' %}">
  {% endblock %}
  <link href="{% static 'polo/css/plugins.css' %}" rel="stylesheet">
  <link href="{% static 'polo/scss/style.css' %}" rel="stylesheet">
  <link href="{% static 'polo/css/custom.css' %}?date={% now 'Ymd' %}" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'plugins/select2/select2.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/toastr/toastr.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/lightbox/css/lightbox.min.css' %}">
  <link rel="stylesheet" href="{% static 'plugins/trumbowyg/ui/trumbowyg.min.css' %}">

  {% block head_extra %}
  {% endblock %}
</head>
<body>
{% block body %}
  <div id="topbar" class="dark topbar-fullwidth">
    <div class="container">
      <div class="row">
        <div class="col-md-6">
          <ul class="top-menu">
            {% if request.user.is_staff %}
            <li>
              <a href="/admin/">
                <i class="fa fa-cog"></i>
                Administration
              </a>
            </li>
            <li>
              <a href="{% url 'orgues:dashboard' %}"> <i class="fa fa-chart-line"></i> Dashboard</a>
            </li>
            {% endif %}
            <li>
              <a href="https://github.com/inventaire-des-orgues/portail/projects/1">
                <i class="fa fa-columns"></i>
                Code source
              </a></li>
            {% if request.user.is_authenticated %}
              <li>
                <a href="{% url 'accounts:mon-compte' %}">
                  <i class="fa fa-user"></i>
                  Mon compte
                </a>
              </li>
              <li>
                <a href="{% url 'logout' %}">
                  <i class="fa fa-sign-out-alt"></i>
                  Déconnexion
                </a>
              </li>
            {% else %}
              <li>
                <a href="{% url 'login' %}">
                  <i class="fa fa-sign-out-alt"></i>
                  Connexion
                </a>
              </li>
              <li>
                <a href="{% url 'accounts:inscription' %}">
                  <i class="far fa-user"></i>
                  Inscription
                </a>
              </li>
            {% endif %}
          </ul>
        </div>
        <div class="col-md-6 d-none d-sm-block">
          <div class="social-icons social-icons-colored-hover">
            <ul>
              <li class="social-en"><a href="{% url 'contact' %}"><i class="fa fa-envelope"></i></a></li>
              <li class="social-facebook"><a href="https://fr-fr.facebook.com/orgueenfrance/"><i class="fab fa-facebook-f"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>


  <section id="logo-header">
    <a class="" href="https://docs.inventaire-des-orgues.fr" id="lien-documentation" target="_blank" rel="noopener noreferrer">
      <i class="far text-dark fa-question-circle"></i>
    </a>
    <div class="container">
      <div class="page-title view zoom">
        <a href="/">
          <img src="{% static 'img/logo.png' %}" alt="" width="200px">
        </a>
      </div>
    </div>
  </section>
  <!-- end: Page title -->
  <!-- Page Menu -->
  <div class="page-menu menu-outline">
    <div class="container">
      <nav>
        <ul>
          <li>
            <a href="{% url 'accueil' %}">Accueil</a>
          </li>
          <li>
            <a href="{% url 'orgues:orgue-carte' %}">Carte</a>
          </li>
          <li>
            <a href="{% url 'orgues:orgue-list' %}">Les orgues</a>
          </li>
          <li>
            <a href="{% url 'lexique' %}">Lexique</a>
          </li>
          <li>
            <a href="https://docs.inventaire-des-orgues.fr/faq/" target="_blank" rel="noopener noreferrer">Questions/Réponses</a>
          </li>
        </ul>
      </nav>
      <div id="pageMenu-trigger">
        <i class="fa fa-lg fa-bars" style="color: #5c1c54"></i>
      </div>
    </div>
  </div>
  {% block content %}
    <section id="page-content">
    </section>
  {% endblock %}
  {% block modal %}
  {% endblock %}

  {% include 'footer.html' %}
{% endblock %}
<script src="{% static 'polo/js/jquery.js' %}"></script>
<script src="{% static 'plugins/popper/popper.min.js' %}"></script>
<script src="{% static 'polo/js/plugins.js' %}"></script>
<script src="{% static 'polo/js/functions.js' %}"></script>
<!--<script src="{% static 'plugins/select2/select2.min.js' %}"></script>-->
<script src="{% static 'plugins/select2/select2.full.min.js' %}"></script>
<script src="{% static 'plugins/select2/i18n/fr.js' %}"></script>
<script src="{% static 'plugins/toastr/toastr.min.js' %}"></script>
<script src="{% static 'plugins/lightbox/js/lightbox.min.js' %}"></script>
{% include 'messages.html' %}
<script>
  $(function () {
    $('[data-toggle="tooltip"]').tooltip()
  })
  $(function () {
    $('[data-toggle="tooltip-children"]').hover(
      function(e){$(this).find('.tooltip-children').tooltip('show');},
      function(e){$(this).find('.tooltip-children').tooltip('hide');}
    );
  })
</script>
<script>
  $(".menu-outline ul li a").each(function () {
    if ($(this).attr("href") === window.location.pathname) {
      $(this).parent().addClass("active")
    }
  })
</script>


{% block js_extra %}
{% endblock %}
</body>
</html>

templates/contact.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="bg-primary pt-5" id="contact">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12">
                <h3 class="text-center text-white mb-5">Nous contacter</h3>
            </div>
            <div class="col-lg-9">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-lg-6">
                                <img src="{% static 'img/iso.png' %}" alt="" width="300px" style="display: block; margin: auto">
                                <p>Ici vous pouvez nous contacter si vous avez des recommandations particulières ou bien un problème quelconque avec l'utilisation de l'inventaire des orgues.</p>
                                <p>C'est ici également que vous pouvez signaler un orgue (généralement récent) qui ne serait pas répertorié.</p>
                                <p>Pour cela, envoyez-nous un mail avec les informations suivantes :</p>
                                <p>
                                <ol style="color: #777777; padding-left: 1em">
                                    <li>La région</li>
                                    <li>Le département</li>
                                    <li>La commune</li>
                                    <li>Le nom complet de l'édifice (ex : église Saint-Cyr-et-Sainte-Julitte)</li>
                                </ol>
                                </p>
                                <p>Au préalable, nous vous remercions de bien vérifier que l'orgue n'est pas déjà présent. Voici notamment quelques difficultés courantes :</p>
                                <p>
                                <ol style="color: #777777; padding-left: 1em">
                                    <li>Le nom d'édifice est-il exact ? (Parfois, plusieurs dénominations existent)</li>
                                    <li>La commune recherchée n'a-t-elle pas fusionné avec une autre ?</li>
                                </ol>
                                </p>
                                <p>Nous traiterons votre demande au plus vite.</p>
                            </div>
                            <div class="col-lg-6"> {% include 'contact_form.html' %}</div>
                        </div>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
{% endblock %}


{% block js_extra %}

<script src="https://www.google.com/recaptcha/api.js"></script>
  <script>
    function onSubmit(token) {
      document.getElementById("contact-form").submit();
    }
  </script>
{% endblock %}

templates/contact_form.html
{% if form.errors %}
  {% for error in user_form.non_field_errors %}
    <div class="alert alert-danger">
      <strong>{{ error|escape }}</strong>
    </div>
  {% endfor %}
{% endif %}

<form action="" method="post" id="contact-form" enctype="multipart/form-data">{% csrf_token %}
  {% for field in form %}
    {% if forloop.last %}
      {{ field }}
    {% else %}
      {% include 'stack_field.html' with with_helptext='true' %}
    {% endif %}
  {% endfor %}
  <hr>
  <div class="form-group text-right">
    <button type="submit" class="btn btn-primary rounded-pill g-recaptcha"
        data-sitekey="6LcJ1rgZAAAAABsMEd0iPcdTLq8w92B5S0CJUSG_"
        data-callback='onSubmit'
        data-action='submit'
    >Envoyer
    </button>
  </div>
</form>

templates/footer.html
{% load static %}
<footer id="footer" class="inverted">
  <div class="footer-content">
    <div class="container">
      <div class="row align-items-top">
        <!--
        <div class="col-lg-3 mt-4 testimg">
          <img src="{% static 'img/logo-nb.png' %}" alt="" style="width:150px; display:block; margin-left: auto; margin-right: auto;">
        </div>
        -->
        <div class="col-lg-3 mt-4">
          <img src="{% static 'img/orgue-en-france.png' %}" alt="" style="width:160px; display:block; margin-left: auto; margin-right: auto; margin-bottom: auto;">
        </div>
        <div class="col-lg-3 mt-4">
          <img src="{% static 'img/Soutenu_ministere_culture.png' %}" alt="" style="width:160px; display:block; margin-left: auto; margin-right: auto;">
        </div>
        <div class="col-lg-3 mt-4">
          <img src="{% static 'img/logo-facteurs-neg.png' %}" alt="" style="width:160px; display:block; margin-left: auto; margin-right: auto;">
        </div>
        <div class="col-lg-3 mt-4">
          <img src="{% static 'img/FFAO.png' %}" alt="" style="width:160px; display:block; margin-left: auto; margin-right: auto;">
        </div>
      </div>
      <div class="row align-items-top">
        <div class="col-lg-4 mt-4">
          <img src="{% static 'img/logo_bretagne.png' %}" alt="" style="width:160px; display:block; margin-left: 55%">
        </div>
        <div class="col-lg-4 mt-4">
          <img src="{% static 'img/logo_bourgogne.png' %}" alt="" style="width:160px; display:block; margin-left: auto; margin-right: auto;">
        </div>
        <div class="col-lg-4 mt-4">
          <img src="{% static 'img/logo_CVL.png' %}" alt="" style="width:140px; display:block; margin-right: 100%;">
        </div>
      </div>
      <div class="row align-items-top">
        <div class="col-lg-4 mt-4">
          <img src="{% static 'img/logo_OPL.png' %}" alt="" style="width:160px; display:block; margin-left: 45%">
        </div>
        <div class="col-lg-4 mt-4">
          <img src="{% static 'img/logo_adora.png' %}" alt="" style="width:160px; display:block; margin-left: auto; margin-right: auto;">
        </div>
        <div class="col-lg-4 mt-4">
          <img src="{% static 'img/logo_paris.png' %}" alt="" style="width:200px; display:block; margin-right: 50%;">
        </div>
      </div>
    </div>
  </div>
  </div>
  <div class="footer-content">
    <div class="container">
      <div class="row align-items-top">
        <div class="col-lg-2 mt-2"></div>
        <div class="col-lg-3 mt-4">
          <div class="widget">
            <div class="widget-title">Liens</div>
            <ul class="list">
              <li>
                <a href="{% url 'accueil' %}">Accueil</a>
              </li>
              {% if user.is_staff %}
              <li>
                <a href="{% url 'accounts:access-logs' %}">Logs</a>
              </li>
              {% endif %}
              <li>
                <a href="{% url 'orgues:orgue-carte' %}">Carte</a>
              </li>
              <li>
                <a href="{% url 'orgues:orgue-list' %}">Les orgues</a>
              </li>
              <li>
                <a class="" href="https://vocabulaire.inventaire-des-orgues.fr">Lexique</a>
              </li>
              <li>
                <a class="" href="{% url 'contact' %}">Contact</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-3 mt-4">
          <div class="widget">
            <div class="widget-title">Contribuer</div>
            {% if request.user.is_authenticated %}
              Vous êtes connecté(e) en temps que "{{ request.user }}"
            {% endif %}
            <ul class="list">
              <li>
                {% if request.user.is_authenticated %}
                  <a href="{% url 'logout' %}">Déconnexion</a>
                {% else %}
                  <a href="{% url 'login' %}">Se connecter</a>
                {% endif %}
              </li>
              <li>
                <a class="" href="https://docs.inventaire-des-orgues.fr" target="_blank" rel="noopener noreferrer">Aide</a>
              </li>
              <li>
                <a href="https://docs.inventaire-des-orgues.fr/charte-du-contributeur/">Charte du contributeur</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-3 mt-4">
          <div class="widget">
            <div class="widget-title">Développer</div>
            <ul class="list">
              <li>
                <a href="https://github.com/inventaire-des-orgues/portail/projects/1" target="_blank" rel="noopener noreferrer">Projet Github du portail</a>
              </li>
              <li>
                <a href="https://github.com/inventaire-des-orgues/portail/issues">Tickets Github du portail</a>
              </li>
              <li>
                <a href="https://github.com/orgs/inventaire-des-orgues/projects/1">Projet Inventaire sur Github</a>
              </li>
                <li>
                <a href="https://github.com/inventaire-des-orgues/docs/issues">Tickets Github de la doc</a>
              </li>
                <li>
                <a href="https://github.com/inventaire-des-orgues/indexes/issues">Tickets Github des données</a>
              </li>
            </ul>
          </div>
        </div>
        <div class="col-lg-2 mt-2"></div>
      </div>
    </div>
  </div>
  </div>
  <div class="copyright-content">
    <div class="container">
      <div class="copyright-text text-center text-light">Inventaire des orgues - <a href="https://docs.inventaire-des-orgues.fr/mentions-legales/" target="_blank" rel="noopener noreferrer">Mentions légales</a> - Développement :
        <a href="https://fabdev.fr" target="_blank" rel="noopener noreferrer">FABDEV</a> et contributeurs - Design : Guillaume Lechevalier-Boissel & FABDEV - <a href="https://github.com/inventaire-des-orgues/portail" target="_blank" rel="noopener noreferrer">Code source</a>
      </div>
    </div>
  </div>
</footer>