orgues/urls.py
from django.urls import path

import orgues.views as v

app_name = 'orgues'
urlpatterns = [
    path('orgues/', v.OrgueList.as_view(), name='orgue-list'),
    path('orgues/csv/', v.OrgueExport.as_view(), name='orgue-csv'),
    path('recherche/', v.OrgueSearch.as_view(), name='orgue-search'),
    path('liste.json', v.OrgueListJS.as_view(), name='orgue-list-js'),
    path('etats.json', v.OrgueEtatsJS.as_view(), name='orgue-etats-js'),
    path('etats2.json', v.OrgueEtatsJSDep.as_view(), name='orgue-etats-js2'),
    path('references_palissy.json', v.OrgueHistJS.as_view(), name='orgue-hist-js'),
    path('references_palissyDep.json', v.OrgueHistJSDep.as_view(), name='orgue-histDep-js'),
    path('carte/', v.OrgueCarte.as_view(), name='orgue-carte'),
    path('detail/<slug:slug>/', v.OrgueDetail.as_view(), name='orgue-detail'),
    path('detail/<slug:slug>/qrcode', v.OrgueQrcode.as_view(), name='orgue-qrcode'),
    path('exemple/', v.OrgueDetailExemple.as_view(), name='orgue-detail-exemple'),
    path('conseils/', v.ConseilsFicheView.as_view(),name='orgue-fiche-conseils'),
    path('orgues/filtre', v.OrgueFiltreJS.as_view(), name='orgue-filtre-js'),
    path('avancement.json', v.Avancement.as_view(), name = 'orgue-av-js'),

    # Administration
    path('creation/', v.OrgueCreate.as_view(), name='orgue-create'),
    path('edition/<uuid:orgue_uuid>/', v.OrgueUpdate.as_view(), name='orgue-update'),
    path('edition/instrumentale/<uuid:orgue_uuid>/', v.OrgueUpdateInstrumentale.as_view(), name='orgue-update-instrumentale'),
    path('edition/composition/<uuid:orgue_uuid>/', v.OrgueUpdateComposition.as_view(), name='orgue-update-composition'),
    path('edition/avancement/<uuid:orgue_uuid>/', v.OrgueDetailAvancement.as_view(), name='orgue-detail-avancement'),
    path('edition/contributions/<uuid:orgue_uuid>/', v.OrgueDetailContributions.as_view(), name='orgue-detail-contributions'),
    path('edition/buffet/<uuid:orgue_uuid>/', v.OrgueUpdateBuffet.as_view(), name='orgue-update-buffet'),
    path('edition/localisation/<uuid:orgue_uuid>/', v.OrgueUpdateLocalisation.as_view(), name='orgue-update-localisation'),
    path('suppression/<uuid:orgue_uuid>/', v.OrgueDelete.as_view(), name='orgue-delete'),
    path('dashboard/', v.Dashboard.as_view(), name='dashboard'),

    # Tableau de bord
    #path('orgues/dashboard', v.OrgueDashboard.as_view(), name='orgue-dashboard'),

    # Evenements
    path('evenements/<uuid:orgue_uuid>/', v.EvenementList.as_view(), name='evenement-list'),
    path('evenement/edition/<int:pk>/', v.EvenementUpdate.as_view(), name='evenement-update'),
    path('evenement/creation/<uuid:orgue_uuid>/', v.EvenementCreate.as_view(), name='evenement-create'),
    path('evenement/suppression/<int:pk>/', v.EvenementDelete.as_view(), name='evenement-delete'),

    # claviers
    path('clavier/creation/<uuid:orgue_uuid>/', v.ClavierCreate.as_view(), name='clavier-create'),
    path('clavier/edition/<int:pk>/', v.ClavierUpdate.as_view(), name='clavier-update'),
    path('clavier/suppression/<int:pk>/', v.ClavierDelete.as_view(), name='clavier-delete'),

    # facteurs
    path('listeFacteur.json', v.FacteurListJSLeaflet.as_view(), name='facteur-list-js-leaflet'),
    path('js/facteurs/', v.FacteurListJS.as_view(), name='facteur-list-js'),
    path('js/facteurs/creation/', v.FacteurCreateJS.as_view(), name='facteur-create-js'),
    path('js/facteurs/lonlat/', v.FacteurListJSlonlat.as_view(), name='facteur-list-js-lonlat'),
    path('js/facteurs/lonlatLeaflet/', v.FacteurLonLatLeaflet.as_view(), name='facteur-js-lonlat'),

    # types jeux
    path('types_jeux/creation/', v.TypeJeuCreateJS.as_view(), name='typejeu-create-js'),
    path('types_jeux/edition/<int:pk>/', v.TypeJeuUpdate.as_view(), name='typejeu-update'),
    path('js/liste/jeux/', v.TypeJeuListJS.as_view(), name='typejeu-list-js'),

    # fichiers
    path('fichiers/<uuid:orgue_uuid>/', v.FichierList.as_view(), name='fichier-list'),
    path('fichiers/creation/<uuid:orgue_uuid>/', v.FichierCreate.as_view(), name='fichier-create'),
    path('fichiers/suppression/<int:pk>/', v.FichierDelete.as_view(), name='fichier-delete'),

    # images
    path('images/<uuid:orgue_uuid>/', v.ImageList.as_view(), name='image-list'),
    path('images/creation/<uuid:orgue_uuid>/', v.ImageCreate.as_view(), name='image-create'),
    path('images/update/<int:pk>/', v.ImageUpdate.as_view(), name='image-update'),
    path('images/suppression/<int:pk>/', v.ImageDelete.as_view(), name='image-delete'),
    path('images/principale/<int:pk>/', v.ImagePrincipaleUpdate.as_view(), name='image-principale'),

    # Sources
    path('sources/<uuid:orgue_uuid>/', v.SourceList.as_view(), name='source-list'),
    path('source/edition/<int:pk>/', v.SourceUpdate.as_view(), name='source-update'),
    path('source/creation/<uuid:orgue_uuid>/', v.SourceCreate.as_view(), name='source-create'),
    path('source/suppression/<int:pk>/', v.SourceDelete.as_view(), name='source-delete'),

    path('searchlog/', v.SearchLogView.as_view(), name='search-log'),

    #Création d'orgue
    path('js/communes/', v.CommuneListJS.as_view(), name='commune-list-js'),
    path('js/designation/', v.DesignationListJS.as_view(), name='designation-list-js')
]

orgues/models.py
import os
import re
import uuid

import meilisearch
from django.conf import settings
from django.core.exceptions import ValidationError
from django.core.validators import RegexValidator
from django.db import models
from django.db.models.signals import post_save, post_delete
from django.dispatch import receiver
from django.urls import reverse
from django.utils.text import slugify
from imagekit.models import ImageSpecField, ProcessedImageField
from pilkit.processors import ResizeToFill, ResizeToFit, Transpose
from PIL import Image as PilImage
from django import forms

from accounts.models import User


class Facteur(models.Model):
    """
    Pas celui qui distribue le courrier
    """
    nom = models.CharField(max_length=100)
    latitude_atelier = models.FloatField(null=True, blank=True, verbose_name="Latitude de l'atelier")
    longitude_atelier = models.FloatField(null=True, blank=True, verbose_name="Longitude de l'atelier")
    updated_by_user = models.ForeignKey(User, null=True, editable=False, on_delete=models.SET_NULL)

    def __str__(self):
        return self.nom

    class Meta:
        ordering = ['latitude_atelier']


class Orgue(models.Model):
    CHOIX_TYPE_OSM = (
        ("node", "Nœud (Node)"),
        ("way", "Chemin (Way)"),
        ("relation", "Relation (Relation)"),
    )

    CHOIX_PROPRIETAIRE = (
        ("commune", "Commune"),
        ("interco", "Intercommunalité"),
        ("etat", "Etat"),
        ("association_culturelle", "Association culturelle"),
        ("diocese", "Diocèse"),
        ("paroisse", "Paroisse"),
        ("congregation", "Congrégation"),
        ("etablissement_scolaire", "Etablissement scolaire"),
        ("conservatoire", "Conservatoire ou Ecole de musique"),
        ("hopital", "Hôpital"),
    )

    CHOIX_ETAT = (
        ('tres_bon', "Très bon, tout à fait jouable"),
        ('bon', "Bon : jouable, défauts mineurs"),
        ('altere', "Altéré : difficilement jouable"),
        ('degrade', "Dégradé ou en ruine : injouable"),
        ('restauration', "En restauration (ou projet initié)")
    )

    CHOIX_TRANSMISSION = (
        ("mecanique", "Mécanique"),
        ("mecanique_suspendue", "Mécanique suspendue"),
        ("mecanique_balanciers", "Mécanique à balanciers"),
        ("mecanique_barker", "Mécanique Barker"),
        ("numerique", "Numérique"),
        ("electrique", "Electrique"),
        ("electrique_proportionnelle", "Electrique proportionnelle"),
        ("electro_pneumatique", "Electro-pneumatique"),
        ("pneumatique", "Pneumatique"),
    )

    CHOIX_TIRAGE = (
        ("mecanique", "Mécanique"),
        ("pneumatique_haute_pression", "Pneumatique haute pression"),
        ("pneumatique_basse_pression", "Pneumatique basse pression"),
        ("numerique", "Numérique"),
        ("electrique", "Electrique"),
        ("electro_pneumatique", "Electro-pneumatique"),
    )

    CHOIX_REGION = (
        ('Auvergne-Rhône-Alpes', 'Auvergne-Rhône-Alpes'),
        ('Bourgogne-Franche-Comté', 'Bourgogne-Franche-Comté'),
        ('Bretagne', 'Bretagne'),
        ('Centre-Val de Loire', 'Centre-Val de Loire'),
        ('Corse', 'Corse'),
        ('Grand Est', 'Grand Est'),
        ('Guadeloupe', 'Guadeloupe'),
        ('Guyane', 'Guyane'),
        ('Hauts-de-France', 'Hauts-de-France'),
        ('Île-de-France', 'Île-de-France'),
        ('La Réunion', 'La Réunion'),
        ('Martinique', 'Martinique'),
        ('Normandie', 'Normandie'),
        ('Nouvelle-Aquitaine', 'Nouvelle-Aquitaine'),
        ('Nouvelle-Calédonie', 'Nouvelle-Calédonie'),
        ('Occitanie', 'Occitanie'),
        ('Pays de la Loire', 'Pays de la Loire'),
        ("Provence-Alpes-Côte d'Azur", "Provence-Alpes-Côte d'Azur"),
        ('Saint-Pierre-et-Miquelon', 'Saint-Pierre-et-Miquelon')
    )

    CHOIX_DEPARTEMENT = (
        ('01', 'Ain'),
        ('02', 'Aisne'),
        ('03', 'Allier'),
        ('04', 'Alpes-de-Haute-Provence'),
        ('05', 'Hautes-Alpes'),
        ('06', 'Alpes-Maritimes'),
        ('07', 'Ardèche'),
        ('08', 'Ardennes'),
        ('09', 'Ariège'),
        ('10', 'Aube'),
        ('11', 'Aude'),
        ('12', 'Aveyron'),
        ('13', 'Bouches-du-Rhône'),
        ('14', 'Calvados'),
        ('15', 'Cantal'),
        ('16', 'Charente'),
        ('17', 'Charente-Maritime'),
        ('18', 'Cher'),
        ('19', 'Corrèze'),
        ('2A', 'Corse-du-Sud'),
        ('2B', 'Haute-Corse'),
        ("21", "Côte-d'Or"),
        ("22", "Côtes-d'Armor"),
        ('23', 'Creuse'),
        ('24', 'Dordogne'),
        ('25', 'Doubs'),
        ('26', 'Drôme'),
        ('27', 'Eure'),
        ('28', 'Eure-et-Loir'),
        ('29', 'Finistère'),
        ('30', 'Gard'),
        ('31', 'Haute-Garonne'),
        ('32', 'Gers'),
        ('33', 'Gironde'),
        ('34', 'Hérault'),
        ('35', 'Ille-et-Vilaine'),
        ('36', 'Indre'),
        ('37', 'Indre-et-Loire'),
        ('38', 'Isère'),
        ('39', 'Jura'),
        ('40', 'Landes'),
        ('41', 'Loir-et-Cher'),
        ('42', 'Loire'),
        ('43', 'Haute-Loire'),
        ('44', 'Loire-Atlantique'),
        ('45', 'Loiret'),
        ('46', 'Lot'),
        ('47', 'Lot-et-Garonne'),
        ('48', 'Lozère'),
        ('49', 'Maine-et-Loire'),
        ('50', 'Manche'),
        ('51', 'Marne'),
        ('52', 'Haute-Marne'),
        ('53', 'Mayenne'),
        ('54', 'Meurthe-et-Moselle'),
        ('55', 'Meuse'),
        ('56', 'Morbihan'),
        ('57', 'Moselle'),
        ('58', 'Nièvre'),
        ('59', 'Nord'),
        ('60', 'Oise'),
        ('61', 'Orne'),
        ('62', 'Pas-de-Calais'),
        ('63', 'Puy-de-Dôme'),
        ('64', 'Pyrénées-Atlantiques'),
        ('65', 'Hautes-Pyrénées'),
        ('66', 'Pyrénées-Orientales'),
        ('67', 'Bas-Rhin'),
        ('68', 'Haut-Rhin'),
        ('69', 'Rhône'),
        ('70', 'Haute-Saône'),
        ('71', 'Saône-et-Loire'),
        ('72', 'Sarthe'),
        ('73', 'Savoie'),
        ('74', 'Haute-Savoie'),
        ('75', 'Paris'),
        ('76', 'Seine-Maritime'),
        ('77', 'Seine-et-Marne'),
        ('78', 'Yvelines'),
        ('79', 'Deux-Sèvres'),
        ('80', 'Somme'),
        ('81', 'Tarn'),
        ('82', 'Tarn-et-Garonne'),
        ('83', 'Var'),
        ('84', 'Vaucluse'),
        ('85', 'Vendée'),
        ('86', 'Vienne'),
        ('87', 'Haute-Vienne'),
        ('88', 'Vosges'),
        ('89', 'Yonne'),
        ('90', 'Territoire de Belfort'),
        ('91', 'Essonne'),
        ('92', 'Hauts-de-Seine'),
        ('93', 'Seine-Saint-Denis'),
        ('94', 'Val-de-Marne'),
        ("95", "Val-d'Oise"),
        ('971', 'Guadeloupe'),
        ('972', 'Martinique'),
        ('976', 'Mayotte'),
        ('973', 'Guyane'),
        ('974', 'La Réunion'),
        ('975', 'Saint-Pierre-et-Miquelon'),
        ('988', 'Nouvelle-Calédonie'),

    )

    # Informations générales
    designation = models.CharField(max_length=300, null=True, verbose_name="Désignation", default="orgue", blank=True)
    is_polyphone = models.BooleanField(default=False, verbose_name="Orgue polyphone de la manufacture Debierre ?")
    codification = models.CharField(max_length=24, unique=True, db_index=True)
    references_palissy = models.CharField(max_length=60, null=True, verbose_name="Référence(s) Palissy pour les monuments historiques.", blank=True,
                                          help_text="Séparer les codes par des virgules.")
    references_inventaire_regions = models.CharField(verbose_name = "Code inventaire régional", max_length=60, null=True, blank=True)
    resume = models.TextField(max_length=500, null=True, verbose_name="Résumé", blank=True,
                              help_text="Présentation en quelques lignes de l'instrument \
                              en insistant sur son originalité (max 500 caractères).")
    proprietaire = models.CharField(max_length=40, null=True, choices=CHOIX_PROPRIETAIRE, default="commune",
                                    verbose_name="Propriétaire")
    organisme = models.CharField(verbose_name="Organisme auquel s'adresser", max_length=100, null=True, blank=True,
                                 help_text="Notamment pour accéder à l'instrument.")
    lien_reference = models.URLField(verbose_name="Lien de référence", max_length=300, null=True, blank=True)

    entretien = models.ManyToManyField(Facteur, blank=True, verbose_name="Facteur en charge de l'entretien")

    etat = models.CharField(max_length=20, choices=CHOIX_ETAT, null=True, blank=True,
                            help_text="Se rapporte au fait que l'orgue est jouable ou non.")
    emplacement = models.CharField(max_length=50, null=True, blank=True, verbose_name="Emplacement",
                                   help_text="Ex: sol, tribune ...")
    buffet = models.TextField(verbose_name="Description du buffet", null=True, blank=True,
                              help_text="Description du buffet et de son état.")
    console = models.TextField(verbose_name="Description de la console", null=True, blank=True,
                               help_text="Description de la console (ex: en fenêtre, \
                               séparée organiste tourné vers l'orgue ...).")

    commentaire_admin = models.TextField(verbose_name="Commentaire contributeurs", null=True, blank=True,
                                         help_text="Commentaire uniquement visible par les contributeurs.")

    # Localisation
    code_dep_validator = RegexValidator(regex='^(97[12346]|0[1-9]|[1-8][0-9]|9[0-5]|2[AB])$',
                                        message="Renseigner un code de département valide")

    edifice = models.CharField(max_length=300)
    adresse = models.CharField(max_length=300, null=True, blank=True)
    commune = models.CharField(max_length=100)
    code_insee = models.CharField(max_length=5, verbose_name="Code_INSEE")
    ancienne_commune = models.CharField(max_length=100, null=True, blank=True)

orgues/api/views.py
from rest_framework import viewsets
from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.renderers import JSONRenderer

from orgues.api.serializers import OrgueSerializer
from orgues.models import Orgue, Facteur, Accessoire, TypeClavier, TypeJeu


class OrgueViewSet(viewsets.ReadOnlyModelViewSet):
    queryset = Orgue.objects.all()
    serializer_class = OrgueSerializer


    def get_queryset(self):
        queryset = Orgue.objects.all()
        code_departement = self.request.query_params.get('code_departement', None)
        if code_departement is not None:
            queryset = queryset.filter(code_departement=code_departement)
        return queryset.order_by('designation')


class ConfigView(APIView):
    renderer_classes = [JSONRenderer]

    def get(self, request, format=None):
        facteurs = Facteur.objects.all()
        accessoires = Accessoire.objects.all()
        typesClavier = TypeClavier.objects.all()
        typesJeux = TypeJeu.objects.all()
        return Response({
            "facteurs": [facteur.nom for facteur in facteurs],
            "types_claviers": [type.nom for type in typesClavier],
            "types_jeux": [{"nom": type.nom, "hauteur": type.hauteur} for type in typesJeux],
            "type_accessoire": [accessoire.nom for accessoire in accessoires]
        })

orgues/templates/orgues/mosaique.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>$Title$</title>
</head>
<body>
$END$
</body>
</html>

orgues/templates/orgues/orgue_list.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
  <div class="container" id="app">
    <section id="orgue-list">
      <div class="row">
        <div class="col-xl-4">
          <div class="card">
            <div class="card-body" id="search-form">
              <div class="form-group">
                <label for="">Département</label>
                <select v-model="departement" class="form-control">
                  <option value="">Tous les départements</option>
                  <option v-for="departement in departements" :value="departement[1]">((departement[0])) ((departement[1]))</option>
                </select>
              </div>
              <div class="form-group">
                <label for="query">Recherche <i class="fa fa-info-circle tex-primary" data-toggle="tooltip" data-title="Rechercher une commune, une église, un facteur ..."></i></label>
                <input id="query" v-model="input" placeholder="Commune, facteur, église ..." class="form-control" value="{{ request.GET.facteur }}"/>
              </div>
              <div class="text-center d-none d-xl-block">
                <img src="{% static 'img/conseil_image_principale.png' %}" alt="" style="width: 100%">
              </div>
              <div class="text-center d-none d-xl-block">

                <h5>Quelques conseils pour éditer la photo principale d'une fiche d'orgue</h5>

                <a href="{% url 'orgues:orgue-fiche-conseils' %}" class="btn btn-primary rounded-pill mt-3 btn-block">voir les
                  recommandations</a>
                <hr>

                {% if perms.orgues.change_orgue %}
                <a href="{% url 'orgues:orgue-csv' %}" class="btn btn-warning rounded-pill mt-3 btn-block">
                    Export des orgues en csv</a>
                {% endif %}
                <hr>

                {% if perms.orgues.add_orgue %}
                <a href="{% url 'orgues:orgue-create' %}" class="btn btn-info rounded-pill mt-3 btn-block">
                    Créer un nouvel orgue</i></a>
                {% endif %}
              </div>
            </div>
          </div>
        </div>
        <div class="col-xl-8" v-cloak>
          <p class="text-muted text-center" v-if="!loading">((hits)) orgue<span v-if="hits>0">s</span></p>
          <div class="card" v-if="loading">
            <div class="card-body">
              <div class="d-flex align-items-center">
                <strong>Chargement...</strong>
                <div class="spinner-border ml-auto" role="status" aria-hidden="true"></div>
              </div>
            </div>
          </div>
          <div v-for="orgue in orgues" class="card shadow-sm vignette mb-lg-4 mb-sm-5 orgue-card" @click="select(orgue)">
            <div class="row no-gutters">
              <div class="col-lg-4 la_vignette" style="background: #868e96;">
                <img class="card-img-top" :src="orgue.vignette" alt="Photo orgue" style="">
              </div>
              <div class="col-lg-8">
                <div class="card-body py-md-3">
                  <h4 class="card-title mb-0">
                    <span v-html="orgue._formatted.edifice"></span>
                    | <span v-html="orgue._formatted.commune"></span>, <span v-html="orgue.departement"></span>
                  </h4>
                  {% spaceless %}
                    <p class=" my-0">
                      <span v-html="orgue.designation"></span>
                      <span v-if="!orgue.designation">Orgue</span>
                      <span v-if="orgue.emplacement">, ((orgue.emplacement))</span>
                      <span v-if="orgue.resume_composition">, ((orgue.resume_composition))</span>
                    </p>
                  {% endspaceless %}
                  {% spaceless %}
                    <p class="my-0">
                      <b>Localisation : </b>
                      <span v-html="orgue._formatted.commune"></span>
                      <span v-if="orgue.ancienne_commune">(</span>
                      <span v-html="orgue._formatted.ancienne_commune" v-if="orgue.ancienne_commune"></span>
                      <span v-if="orgue.ancienne_commune">)</span>,
                      <span v-html="orgue._formatted.departement"></span>
                      (<span v-html="orgue._formatted.region"></span>)
                    </p>
                  {% endspaceless %}
                  <p class="my-0" v-if="orgue.facteurs.length > 0">
                    <b>Facteurs :</b> <span v-html="orgue._formatted.facteurs"></span>
                  </p>
                  {% if user.is_authenticated %}
                    <p class="my-1 d-none d-md-block" style="position:absolute;bottom:5px;right:20px; color:#5C1C54">
                      Avancement : ((orgue.completion)) %</p>
                  {% endif %}
                </div>
                {% if user.is_authenticated %}
                  <div class="card-footer d-md-none" style="color:#5C1C54">Avancement de la fiche
                    : ((orgue.completion))%
                  </div>
                {% endif %}
              </div>
            </div>
          </div>
          <ul class="pagination" v-if="!loading && hits > 0 && page <=pages">
            <li class="page-item">
              <button class="page-link" @click="previous_page" v-if="page > 1">
                <span class="fa fa-chevron-left"></span>
              </button>
            </li>
            <li class="page-item">
              <span class="page-link" style="background:transparent;border:none;width:130px;  ">Page ((page))  / ((pages))</span>
            </li>
            <li class="page-item" v-if="page < pages">
              <button class="page-link" @click="next_page">
                <span class="fa fa-chevron-right"></span>
              </button>
            </li>
          </ul>
          <p class="text-center lead py-50" v-if="!loading && orgues.length == 0">
            L'orgue que vous recherchez n'est pas répertorié ? <br>
            Si cela est le cas vous pouvez le signaler ici <br>
            <a class="btn btn-primary rounded-pill mt-2" href="{% url 'contact' %}">Faire la demande</a>
          </p>
        </div>
      </div>
    </section>
  </div>
{% endblock %}
{% block js_extra %}

  <script src="https://cdn.jsdelivr.net/npm/vue@2.6.0"></script>
  {{ departements|json_script:"departements" }}

  <script>
    var departements = JSON.parse(document.getElementById('departements').textContent);
    var app = new Vue({
      el: '#app',
      data: {
        debouncedInput: '{{ query|default_if_none:'' }}',
        hits: 0,
        page: {% if page %}{{ page}}{% else %}1{% endif %},
        pages: 0,
        loading: false,
        orgues: [],
        departement: '{{ departement|default_if_none:'' }}',
        departements: departements
      },
      created: function () {
        this.fetchData();
      },
      watch: {
        debouncedInput: function () {
          this.page = 1
          this.fetchData()
        },
        departement: function () {
          this.page = 1
          this.fetchData()
        },
      },
      computed: {
        input: {
          get() {
            return this.debouncedInput
          },
          set(val) {
            if (this.timeout) clearTimeout(this.timeout)
            this.timeout = setTimeout(() => {
              this.debouncedInput = val
            }, 300)
          }
        }
      },
      methods: {
        fetchData: function (scrolltop) {
          var scrolltop = scrolltop || false;
          var self = this;
          var query = self.debouncedInput
          var departement = self.departement
          var page = self.page
          this.loading = true

          var pageUrl = '?page=' + page;
          if (departement) {
            pageUrl += '&departement=' + departement
          }
          if (query) {
            pageUrl += '&query=' + query
          }

          $.ajax({
            type: "POST",
            url: "{% url 'orgues:orgue-search' %}",
            data: {
              csrfmiddlewaretoken: '{{ csrf_token }}',
              query: query,
              pageUrl: pageUrl,
              page: page,
              departement: departement
            },
            error: function (resp) {
              self.loading = false
              toastr.error(resp.responseJSON.message)
            },
            success: function (results) {
              self.loading = false
              self.orgues = results.hits
              self.hits = results.nbHits
              self.pages = results.pages
              if (scrolltop) window.scrollTo(0, 0);
              window.history.pushState('', '', pageUrl);
            },
          });
        }
        ,
        previous_page: function () {
          if (this.page <= 0) {
            return
          }
          this.page -= 1;
          this.fetchData(true);
        }
        ,
        next_page: function () {
          if (this.page >= this.pages) {
            return
          }
          this.page += 1;
          this.fetchData(true);
        }
        ,
        select: function (orgue) {
          window.location.href = orgue.url;
        }
      }
      ,
      delimiters: ["((", "))"]
    })
  </script>
{% endblock %}